In [1]:
name = 'leonardo'
nums = [1,2,3,4]

In [2]:
id(name)

2889488844912

In [3]:
id(nums)

2889488650880

In [4]:
nums2 = nums

In [6]:
nums.append(5)

In [7]:
nums

[1, 2, 3, 4, 5]

In [8]:
id(nums)

2889488650880

In [10]:
name = name.upper()

In [11]:
name

'LEONARDO'

In [12]:
id(name)

2889489610416

In [13]:
nums2

[1, 2, 3, 4, 5]

In [14]:
id(nums2)

2889488650880

In [15]:
nums2 = nums.copy()
id(nums2)

2889489687680

In [21]:
sentence = 'a man a plan a canal panama'
sentence = 'a an the a a the an an an'

# a-3
# an-4

# a-3
# man-1
# plan-1

In [16]:
'ab' in 'abracadabra'

True

In [17]:
1 in [1,2,3,4]

True

In [ ]:
# sqs = {1:1, 2:4, 3:9}
sqs = {}
for

In [116]:
emps_data = '''
jai,CEO,1,12324.56
viru,CTO,2,11111.11
basanti,CFO,3,22222.22
'''
emps_data

'\njai,CEO,1,12324.56\nviru,CTO,2,11111.11\nbasanti,CFO,3,22222.22\n'

In [ ]:
find_emp('jai', 'salary')

In [19]:
sqs = {}
for num in range(1,10+1):
    sqs[num] = num**2
    
sqs

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [26]:
word_freq = {}
print(sentence)
for word in sentence.split():
    if word in word_freq:
        word_freq[word] += 1
    else:
        word_freq[word] = 1
        
    print(word_freq)

a an the a a the an an an
{'a': 1}
{'a': 1, 'an': 1}
{'a': 1, 'an': 1, 'the': 1}
{'a': 2, 'an': 1, 'the': 1}
{'a': 3, 'an': 1, 'the': 1}
{'a': 3, 'an': 1, 'the': 2}
{'a': 3, 'an': 2, 'the': 2}
{'a': 3, 'an': 3, 'the': 2}
{'a': 3, 'an': 4, 'the': 2}


In [27]:
def sq(num):
    return num**2

In [41]:
def pbar(nums, char='#'):
    for num in nums:
        print(char*num, num)

In [39]:
pbar([3,1,6,4], '-')

--- 3
- 1
------ 6
---- 4


In [44]:
def calc_freq(sentence):
    word_freq = {}

    for word in sentence.split():
        if word in word_freq:
            word_freq[word] += 1
        else:
            word_freq[word] = 1
    
    return word_freq

In [45]:
calc_freq(sentence)

{'a': 3, 'an': 4, 'the': 2}

In [68]:
def parse(emp_data):
    emps = {}

    for emp_data in emps_data.strip().splitlines():
    #     name, emp_data = emp_data.split(',', 1)
        emp = emp_data.split(',')
        name = emp.pop(0)
        keys = 'desig empid salary'.split()
        emps[name] = dict(zip(keys, emp))

    return emps

def lookup(emps, name, field='empid'):
    return emps[name][field]

In [71]:
emps = parse(emp_data)
lookup(emps, 'jai', field='salary')

'12324.56'

In [57]:
emp = 'jai,CEO,1,12324.56'.split(',')
# key = emp[0]
# value = emp[1:]
key = emp.pop(0)

['jai', 'CEO', '1', '12324.56']

In [59]:
# emps['jai'].split(',')[2]
emps['jai'][2]

'12324.56'

In [61]:
emp = ['CEO', '1', '12324.56']
keys = 'desig empid salary'.split()
# emp = {'desig': 'CEO', 'empid': '1', 'salary': '12324.56'}
# emp['salary']

In [64]:
e = {}
for k,v in zip(keys, emp):
    e[k] = v
    
e

{'desig': 'CEO', 'empid': '1', 'salary': '12324.56'}

In [66]:
dict(zip(keys, emp))

{'desig': 'CEO', 'empid': '1', 'salary': '12324.56'}

In [72]:
list = [1,2,3,4]

In [75]:
list = __builtins__.list

In [77]:
dir(__builtin__);

In [78]:
emps

{'jai': {'desig': 'CEO', 'empid': '1', 'salary': '12324.56'},
 'viru': {'desig': 'CTO', 'empid': '2', 'salary': '11111.11'},
 'basanti': {'desig': 'CFO', 'empid': '3', 'salary': '22222.22'}}

- File I/O
- File Formats
    - json
    - csv/xls  
- Modules/packages

In [79]:
import sys
import os

In [84]:
sys.path
sys.argv

['C:\\Users\\agulati\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py',
 '-f',
 'C:\\Users\\agulati\\AppData\\Roaming\\jupyter\\runtime\\kernel-a2fc551d-a25a-4739-909f-0e9942a200f8.json']

In [86]:
os.getcwd()

'C:\\Users\\agulati\\hsbc'

In [87]:
sys.getrefcount(name)

23

In [88]:
import glob

In [89]:
glob.glob('*.ipynb')

['Day1.ipynb', 'Day2.ipynb']

In [90]:
import re

In [115]:
m = re.search(r'\w+@\w+\.\w+', 'my mail id is abc@def.com. See you.')
# if m is not None:
if m:
    print('Matched')
    print(m.group(0))
else:
    print('Nope')
    

Matched
abc@def.com


In [114]:
m.group(0)

'abc@def.com'

In [105]:
bool(m)

True

In [91]:
def f(n):
    n**2

In [95]:
x = f(10)
x = None

In [94]:
x is None

True

In [101]:
int(False)
bool(10)

True

In [106]:
sum([1,2,3,4])

10

In [107]:
sum([False, True, True])

2

In [120]:
content = '''The textwrap module provides some convenience functions, as well as TextWrapper, the class that does all the work. If you’re just wrapping or filling one or two text strings, the convenience functions should be good enough; otherwise, you should use an instance of TextWrapper for efficiency.'''
print(content)

The textwrap module provides some convenience functions, as well as TextWrapper, the class that does all the work. If you’re just wrapping or filling one or two text strings, the convenience functions should be good enough; otherwise, you should use an instance of TextWrapper for efficiency.


In [119]:
content[:30]

'The textwrap module provides s'

In [121]:
import textwrap as tw

In [122]:
tw.wrap(content)

['The textwrap module provides some convenience functions, as well as',
 'TextWrapper, the class that does all the work. If you’re just wrapping',
 'or filling one or two text strings, the convenience functions should',
 'be good enough; otherwise, you should use an instance of TextWrapper',
 'for efficiency.']

In [125]:
print(tw.fill(content, 40))

The textwrap module provides some
convenience functions, as well as
TextWrapper, the class that does all the
work. If you’re just wrapping or filling
one or two text strings, the convenience
functions should be good enough;
otherwise, you should use an instance of
TextWrapper for efficiency.


In [126]:
2 ** 38

274877906944

In [129]:
chr(ord('')+2)
# chr(65)

'C'

In [130]:
content = '''g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj.'''

In [132]:
for char in content:
    print(chr(ord(char)+2), end='')

i"hope"you"didnt"tr{nsl{te"it"|y"h{nd0"th{ts"wh{t"computers"{re"for0"doing"it"in"|y"h{nd"is"inefficient"{nd"th{t)s"why"this"text"is"so"long0"using"string0m{ketr{ns*+"is"recommended0"now"{pply"on"the"url0

# Data

In [133]:
import numpy as np

In [135]:
arr = np.array([1,2,3,4])

In [136]:
type(arr)

numpy.ndarray

In [137]:
nums = [1,2,3,4]

In [139]:
nums[1:]

[2, 3, 4]

In [141]:
arr[1:]

array([2, 3, 4])

In [143]:
for num in arr:
    print(num)

1
2
3
4


In [144]:
arr.ndim

1

In [145]:
arr.shape

(4,)

In [146]:
arr2d = np.array([[1,2,3],
                  [4,5,6]])

In [147]:
arr2d.ndim

2

In [148]:
arr2d.shape

(2, 3)

In [149]:
nums + [4,5,6]

[1, 2, 3, 4, 4, 5, 6]

In [150]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)

In [152]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [151]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [154]:
arr2 - arr1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [155]:
arr2d + arr1

ValueError: operands could not be broadcast together with shapes (2,3) (10,) 

In [166]:
check = arr1 + 10 == arr2
check

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [167]:
check.dtype

dtype('bool')

In [175]:
arr2d[0][0]
arr2d[0,0]

1

In [178]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
check = arr1>5
check

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [180]:
arr1[check]

array([6, 7, 8, 9])

In [186]:
arr1[(arr1>=3) & (arr1<=7)]

array([3, 4, 5, 6, 7])

In [207]:
np.random.rand(10) * 100 + 100

array([157.6946016 , 165.39318218, 161.56022142, 175.42630462,
       108.81254442, 187.01321281, 102.7032522 , 145.24463078,
       126.93610022, 124.65669708])

In [209]:
np.random.rand(10) * 10 + 90

array([97.26762893, 97.79480487, 96.1046163 , 90.22356287, 95.77106668,
       99.29129273, 91.35266638, 98.84240421, 93.61356045, 97.56423121])

In [ ]:
# sqs on nums from 11-20
# cubes of nums from 1-10
sqs = [100, 121, 169, ..]
cubes = 1

In [215]:
sqs   = np.arange(11,21)**2
cubes = np.arange(1,11)**3

In [216]:
# All values in cubes that are greater than their equiv in squares

array([ 122,  152,  196,  260,  350,  472,  632,  836, 1090, 1400],
      dtype=int32)

In [217]:
sqs

array([121, 144, 169, 196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [218]:
cubes

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [220]:
cubes[cubes > sqs]

array([ 343,  512,  729, 1000], dtype=int32)

In [159]:
np.array([1,'a', 2.4])

array(['1', 'a', '2.4'], dtype='<U32')

In [160]:
arr.dtype

dtype('int32')

In [161]:
2**32

4294967296

In [162]:
2**8

256

In [163]:
arr = np.array([1,2,3,4], dtype=np.int8)

In [165]:
nums = [1,2,3,4]
sys.getsizeof(nums)

88